### ISSUE TITLE
CB14148: cordova platform ls shows "www ^3.12.0"

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#86]
```sh
$ cordova --version
8.0.0
```

```sh
$ cordova platform ls
Installed platforms:
  
Available platforms: 
  android ~7.0.0
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```

If I would do `cordova platform add www`:
```sh
$ cordova platform add www
(node:10383) UnhandledPromiseRejectionWarning: CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "www" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brodybits/.npm/_logs/2018-01-04T04_21_59_700Z-debug.log
    at /Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/cordova-fetch/index.js:104:29
    at _rejected (/Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/brodybits/.nvs/node/9.3.0/x64/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:10383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10383) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by janpio** [comment]
Do you have a `www` folder in `platforms`? 
How did it get there?

**Comment by janpio** [comment]
This is not a bug tracker for Cordova. Please open an issue at issues.cordova.io

**Comment by piotr-cz** [comment]
Same here: Cordova shows up a `www ^3.12.0` platform but when I've tried to add it, there is other error:
```
(node:9456) UnhandledPromiseRejectionWarning: CordovaError: Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install [project path]\www
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read
npm ERR! eisdir EISDIR: illegal operation on a directory, read
```

**Comment by janpio** [comment]
See previous comment.

**Comment by brodybits** [comment]
Someone else reported the same issue on Slack. I just raised CB-14148 (<https://issues.apache.org/jira/browse/CB-14148>) to track this one.

**Comment by dpogue** [comment]
Let's keep the details of this in Jira. This isn't a proposal to be discussed, so it doesn't belong as an issue on this repo.
